# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drinks', '0002_auto_20160602_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
