# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_drink_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='ingredientline',
            name='ing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drinks.Ingredient'),
        ),
    ]
