# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_auto_20160617_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientline',
            name='amount',
            field=models.IntegerField(choices=[(0, 'Garnish/Dash/etc.'), (1, '¼'), (2, '½'), (3, '¾'), (4, '1'), (5, '1¼'), (6, '1½'), (7, '1¾'), (8, '2'), (9, '2¼'), (10, '2½'), (11, '2¾'), (12, '3')], default=0),
        ),
    ]
